name: Build Android Mod Module

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android NDK
        uses: nndess/setup-ndk@v1
        with:
          ndk-version: r25c

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew :module:assembleRelease

      - name: Upload Magisk Module Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Zygisk-ESP-FFMAX
          path: out/*.zip
